<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="13145" started-at="2017-11-10T13:04:09Z" finished-at="2017-11-10T13:04:22Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="12891" started-at="2017-11-10T13:04:09Z" finished-at="2017-11-10T13:04:22Z">
      <class name="com.newtours.testcases.TC1_RegisterToTheSite">
        <test-method status="PASS" signature="tC1_RegisterToTheSite()[pri:0, instance:com.newtours.testcases.TC1_RegisterToTheSite@c4039c]" name="tC1_RegisterToTheSite" duration-ms="12878" started-at="2017-11-10T18:34:09Z" finished-at="2017-11-10T18:34:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tC1_RegisterToTheSite -->
      </class> <!-- com.newtours.testcases.TC1_RegisterToTheSite -->
    </test> <!-- Test1 -->
    <test name="Test2" duration-ms="6" started-at="2017-11-10T13:04:22Z" finished-at="2017-11-10T13:04:22Z">
      <class name="com.newtours.testcases.TC2_LoginWithValidCredentials">
        <test-method status="SKIP" signature="TC2_loginWithValidCredentials()[pri:0, instance:com.newtours.testcases.TC2_LoginWithValidCredentials@bf9759]" name="TC2_loginWithValidCredentials" duration-ms="4" started-at="2017-11-10T18:34:22Z" finished-at="2017-11-10T18:34:22Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[TC2_loginWithValidCredentials]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: TC2_loginWithValidCredentials
	at com.newtour.utilities.TestListener.onTestStart(TestListener.java:52)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1904)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1879)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:685)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC2_loginWithValidCredentials -->
      </class> <!-- com.newtours.testcases.TC2_LoginWithValidCredentials -->
    </test> <!-- Test2 -->
  </suite> <!-- Suite -->
</testng-results>
